### ISSUE TITLE
请问这个是用来干嘛的

### ISSUE THREAD

**Issue by BZMplan** [intxiaoquan/vjudge_lab_helper#2]
如题

**Comment by intchensc** [comment]
用来抓取vjudge中参加contest的题目描述与ac代码，根据提前定义好的word模版自动生成实验报告:)

**Comment by intchensc** [comment]
> 如题

用来抓取vjudge中参加contest的题目描述与ac代码，根据提前定义好的word模版自动生成实验报告:)
